graphhopper:
  datareader.file: map-data/leipzig_germany.osm.pbf # OSM input file (example data)
  graph.location: graph-cache
  graph.flag_encoders: car
  profiles:
    - name: car
      vehicle: car
      weighting: fastest

server:
  application_connectors:
  - type: http
    port: 8989
    # for security reasons bind to localhost
    bind_host: localhost
  admin_connectors:
  - type: http
    port: 8990
    bind_host: localhost